version: "3.7"
services:
  api:
    build: api
    ports:
      - 4040:4040
    volumes:
      - ./api:/app
      - ./tasks:/tasks
    restart: always
    environment:
      - PORT=4040

  frontend:
    build: frontend
    ports:
      - "3030:3030"
    volumes:
      - "./frontend:/app"
    restart: always
    environment:
      - PORT=3030

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticSearchVolume:/usr/share/elasticsearch/data
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

volumes:
  elasticSearchVolume:
    driver: local
